# In order to let this correctly work, install https://github.com/apps/semantic-pull-requests

titleOnly: true
types:
    - "build"
    - "chore"
    - "ci"
    - "deps"
    - "docs"
    - "feat"
    - "fix"
    - "perf"
    - "refactor"
    - "revert"
    - "security"
    - "style"
    - "test"
    - "translation"
