# In order to let this correctly work, install https://github.com/apps/semantic-pull-requests

titleOnly: true
types:
    - "feat"
    - "fix"
    - "docs"
    - "dx"
    - "refactor"
    - "perf"
    - "test"
    - "workflow"
    - "build"
    - "ci"
    - "chore"
    - "types"
    - "wip"
    - "release"
    - "deps"
