#!/bin/bash

echo --------------------------------------------
echo Starting Git hook: prepare-commit-msg

exec < /dev/tty && common/scripts/install-run-rush.js commitizen --hook || true

echo Finished Git hook: prepare-commit-msg
echo --------------------------------------------
