declare module "eslint-plugin-es-x";
declare module "eslint-plugin-html";
declare module "eslint-plugin-no-unsanitized";
declare module "eslint-plugin-react-hooks";
declare module "eslint-plugin-react-perf";
declare module "eslint-plugin-react-refresh";
declare module "eslint-plugin-you-dont-need-lodash-underscore";
declare module "eslint-plugin-validate-jsx-nesting";
declare module "@ospm/eslint-plugin-react-unhookify";
