#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

# The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the commit.

echo --------------------------------------------
echo Starting Git hook: pre-commit

npx lint-staged

yarn pretty-quick --staged

npx sort-package-json

echo Finished Git hook: pre-commit
echo --------------------------------------------
