name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@7d86f5451bc5e671c0910428ee71e79ebadaf94e" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
