name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@78c0eab008e6a0cf4dd4ca579b5177f6d610b5f3" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
