name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@9c000ebdb7571f022d19752c1c38a57e61a63448" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
