name: Build and deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js 12.x
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - name: set git credentials
              run: |
                  git config --local user.email "d.bannert@anolilab.de"
                  git config --local user.name "Daniel Bannert"
            - name: check consistent dependencies
              run: node ./common/scripts/install-run-rush.js check
            - name: check changelog
              run: node ./common/scripts/install-run-rush.js change -v
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: install
              run: node ./common/scripts/install-run-rush.js install
            #            - name: build
            #              run: node ./common/scripts/install-run-rush.js rebuild --verbose
            - name: textlint
              run: node ./common/scripts/install-run-rush.js textlint
            - name: eslint
              run: node ./common/scripts/install-run-rush.js eslint
    #            - name: run unit tests
    #              run: node ./common/scripts/install-run-rush.js jest
    #            - name: upload code coverage to codecov
    #              uses: codecov/codecov-action@v1
    #            - name: run integration tests
    #              run: node ./common/scripts/install-run-rush.js test:integration

    publish:
        needs: build
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js 12.x
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - name: set git credentials
              run: |
                  git config --local user.email "d.bannert@anolilab.de"
                  git config --local user.name "Daniel Bannert"
            - name: install
              run: node ./common/scripts/install-run-rush.js install
            #            - name: build
            #              run: node ./common/scripts/install-run-rush.js rebuild --verbose
            - name: set npm credentials
              run: echo //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN > ~/.npmrc
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            - name: Bump versions
              run: node ./common/scripts/install-run-rush.js version --bump --target-branch main
            - name: publish
              run: node ./common/scripts/install-run-rush.js publish -a -b main -p --set-access-level public --include-all
