name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@b46fcaddf7556a4a0dfeb63033f7acf60d4c4bd3" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
