name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@7d86f5451bc5e671c0910428ee71e79ebadaf94e" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
