name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@5b10e6a2e712406be0b8317df4d437c69b1221ad" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
