name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@b46fcaddf7556a4a0dfeb63033f7acf60d4c4bd3" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
