name: "Lock File Maintenance"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 */3 * * *" # At minute 0 past every 3rd hour.
    pull_request: # yamllint disable-line rule:empty-values
    workflow_dispatch: # yamllint disable-line rule:empty-values

permissions:
    contents: "write" # for checkout and lock file updates

jobs:
    lock-file:
        uses: "anolilab/workflows/.github/workflows/pnpm-lock-file-maintenance.yml@b46fcaddf7556a4a0dfeb63033f7acf60d4c4bd3" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
            node-version: "22.x"
            run-audit-fix: true
        secrets:
            github-token: "${{ secrets.LOCK_MAINTENANCE_GITHUB_TOKEN }}"
