name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@5b10e6a2e712406be0b8317df4d437c69b1221ad" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
