name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@78c0eab008e6a0cf4dd4ca579b5177f6d610b5f3" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
