# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Markdown Lint"

on:
    push:
        paths:
            - "**.md"
    pull_request:
        paths:
            - "**.md"

jobs:
    text-lint:
        name: "Markdown Lint"

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: "Setup node"
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: "14.2.0"

            - name: "Install yarn"
              run: yarn install

            - name: "Cache dependencies"
              uses: actions/cache@v2.1.4
              with:
                  key: npm-${{ hashFiles('yarn.lock') }}
                  path: ~/.npm
                  restore-keys: |
                      npm-

            - name: "Install dependencies"
              run: yarn install

            - run: yarn run lint
