# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Markdown Lint"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - "**.md"
    pull_request:
        paths:
            - "**.md"

jobs:
    text-lint:
        name: "Markdown lint"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@v3"
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@v2.2.4"
              with:
                  version: 8
                  run_install: false

            - name: "Use Node.js 18.x"
              uses: "actions/setup-node@v3"
              with:
                  node-version: "18.x"
                  cache: "pnpm"

            - name: "Get pnpm store directory"
              id: "pnpm-cache"
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: "actions/cache@v3"
              name: "Setup pnpm cache"
              with:
                  path: "${{ steps.pnpm-cache.outputs.STORE_PATH }}"
                  key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            # @see: https://github.com/pnpm/pnpm/issues/4348
            - name: "Upgrade npm to 8.4 version"
              run: "npm install --global npm@8.4"
              env:
                  SKIP_CHECK: "true"

            - name: "Check npm version"
              run: "npm -v"
              env:
                  SKIP_CHECK: "true"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"
              env:
                  SKIP_CHECK: "true"

            - name: "lint"
              run: "pnpm run lint:text"
