name: "Require 'Allow Edits'"

on: ["pull_request_target", "merge_group"] # yamllint disable-line rule:truthy

permissions:
    contents: "read"

jobs:
    check_allow_edits:
        if: github.event_name == 'pull_request_target' # yamllint disable-line rule:quoted-strings
        name: “Require Allow Edits” # yamllint disable-line rule:quoted-strings
        permissions:
            pull-requests: read # yamllint disable-line rule:quoted-strings
        runs-on: ubuntu-latest # yamllint disable-line rule:quoted-strings

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594" # v2.16.0
              with:
                  egress-policy: "audit"

            - uses: "ljharb/require-allow-edits@13f90bc8cc5de000f2b44a0e2c3a11d108e8cd9f" # main
              with:
                  pull_number: "${{ github.event.pull_request.number }}"
