name: "Scorecards supply-chain security"
on: # yamllint disable-line rule:truthy
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@8249d8ea27b21190f8079df71fd7ba0c63f8d352" # v20.2.10
        with:
            branch: "main"
            publish_results: true
