# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Pull Request"

on: # yamllint disable-line rule:truthy
    pull_request_target:
        types:
            - "opened"
            - "edited"
            - "synchronize"

permissions: {}

jobs:
    main:
        permissions:
            pull-requests: "read" # to analyze PRs (amannn/action-semantic-pull-request)
            statuses: "write" # to mark status of analyzed PR (amannn/action-semantic-pull-request)
        runs-on: "ubuntu-latest"
        name: "Semantic Pull Request"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423" # v2.6.0
              with:
                  egress-policy: "audit"

            - name: "Validate PR title"
              uses: "amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f" # v5.4.0
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              with:
                  types: |
                      feat
                      fix
                      chore
                      refactor
                      docs
                      test
                      ci
                      build
                      infra
                      revert
