# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Release"

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

permissions:
  contents: read

jobs:
    test:
        strategy:
            matrix:
                os: ["ubuntu-latest"]
                node_version: ["16", "17", "18", "19"]
                include:
                    - os: "macos-latest"
                      node_version: "16"
                    - os: "windows-latest"
                      node_version: "16"
            fail-fast: false

        name: "Build & Unit Test: node-${{ matrix.node_version }}, ${{ matrix.os }}"

        runs-on: "${{ matrix.os }}"

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
              with:
                egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2"
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4"
              with:
                  version: 8
                  run_install: false

            - name: "Set node version to ${{ matrix.node_version }}"
              uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0"
              with:
                  node-version: "${{ matrix.node_version }}"
                  cache: "pnpm"

            - name: "Get pnpm store directory"
              id: "pnpm-cache"
              run: |
                  echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - uses: "actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1"
              name: "Setup pnpm cache"
              with:
                  path: "${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}"
                  key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"
              env:
                  SKIP_CHECK: "true"

            - name: "test and coverage"
              run: "pnpm run test:coverage"

            - name: "test stylelint config"
              run: "pnpm run test:stylelint"

            - name: "test babel config"
              run: "pnpm run test:babel"

    semantic-release:
        name: "Semantic Release"

        runs-on: "ubuntu-latest"

        needs: ["test"]

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
              with:
                egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2"
              with:
                  fetch-depth: 0
                  persist-credentials: false
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4"
              with:
                  version: 8
                  run_install: false

            - name: "Use Node.js 18.x"
              uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0"
              with:
                  node-version: "18.x"
                  cache: "pnpm"

            - name: "Get pnpm store directory"
              id: "pnpm-cache"
              run: |
                  echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

            - uses: "actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1"
              name: "Setup pnpm cache"
              with:
                  path: "${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}"
                  key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            # @see: https://github.com/pnpm/pnpm/issues/4348
            - name: "Upgrade npm to 8.4 version"
              run: "npm install --global npm@8.4"
              env:
                  SKIP_CHECK: "true"

            - name: "Check npm version"
              run: "npm -v"
              env:
                  SKIP_CHECK: "true"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"

            - name: "Semantic Release"
              if: "success()"
              env:
                  GITHUB_TOKEN: "${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}"
                  NPM_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
                  GIT_AUTHOR_NAME: "github-actions-shell"
                  GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
                  GIT_COMMITTER_NAME: "github-actions-shell"
                  GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
              run: "pnpm multi-semantic-release"

    pnpm-lock-update:
        permissions:
          contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
        name: "pnpm-lock.yaml update"

        runs-on: "ubuntu-latest"

        needs: ["semantic-release"]

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
              with:
                egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2"
              with:
                  fetch-depth: 2
                  token: "${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}"
                  ref: "${{ github.ref }}"
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4"
              with:
                  version: 8
                  run_install: false

            - name: "Use Node.js 18.x"
              uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0"
              with:
                  node-version: "18.x"
                  registry-url: "${{ env.registry_url }}"

            - name: "Update pnpm lock"
              run: "pnpm install --no-frozen-lockfile"

            - name: "Commit modified files"
              uses: "stefanzweifel/git-auto-commit-action@0049e3fa4059ca715255fbbcb7dea4516f02ce0a # v4.15.3"
              with:
                  commit_message: "chore: updated pnpm-lock.yaml"
                  commit_author: "prisis <d.bannert@anolilab.de>"
                  commit_user_email: "d.bannert@anolilab.de"
                  commit_user_name: "prisis"
                  branch: "${{ github.head_ref }}"
