name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@9c000ebdb7571f022d19752c1c38a57e61a63448" # main
        with:
            target-repo: "anolilab/javascript-style-guide"
