name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@ffe1f9c618304dee645c2821890ec3f0a91f67b3" # v21.0.0 # main
        with:
            target-repo: "anolilab/javascript-style-guide"
