name: "Tests"
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    test:
        permissions:
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/test.yml@3bd9e3be8b2c419cf0e9237c1e78ab9a5e68bafa" # v15.1.3+
        with:
            node_versions: '["20", "22", "24"]'
            os_matrix: '["ubuntu-latest"]'
            extra_includes: '[{"os": "macos-latest", "node_version": "20"}, {"os": "windows-latest", "node_version": "20.18"}]'
            pnpm_version: "10"
            test_command: "pnpm test:all"
            coverage: false
