name: "Tests"
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    test:
        permissions:
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/test.yml@20b8733e71ebbb165d54fe8cede47e225985a58a" # v15.3.1+
        with:
            node_versions: '["20", "22", "24"]'
            os_matrix: '["ubuntu-latest"]'
            extra_includes: '[{"os": "macos-latest", "node_version": "20"}, {"os": "windows-latest", "node_version": "20.18"}]'
            test_command: "pnpm test:all"
            coverage: false
