name: "Tests"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    test:
        permissions:
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/test.yml@ffe1f9c618304dee645c2821890ec3f0a91f67b3" # v21.0.0
        with:
            node_versions: '["22", "24"]'
            os_matrix: '["ubuntu-latest"]'
            extra_includes: '[{"os": "macos-latest", "node": "22"}]'
            test_command: "pnpm build:packages && pnpm test:all"
            coverage: false
