# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Yaml Lint"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - "**.yml"
            - "**.yaml"
    pull_request:
        paths:
            - "**.yml"
            - "**.yaml"

permissions:
  contents: read

jobs:
    yaml-lint:
        name: "Yaml lint"

        runs-on: "ubuntu-latest"

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
              with:
                egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2"
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Lint YAML files"
              uses: "ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1"
              with:
                  config_file: ".yamllint.yaml"
                  file_or_dir: "."
                  strict: true
