name: "Zizmor"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@8249d8ea27b21190f8079df71fd7ba0c63f8d352" # v20.2.10
        with:
            min_severity: "medium"
